name: "godot-ci export"
on:
  push:
    tags:
      - '*'

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.3
  PROJECT_NAME: SpaceGoose
  PROJECT_PATH: .
  EXPORT_DIR: build

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    env:
      TAG_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          cd $PROJECT_PATH
          mkdir -v -p $EXPORT_DIR
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/${{ env.PROJECT_NAME }}-windows-${{ env.TAG_NAME }}.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ env.TAG_NAME }}
          path: ${{ env.EXPORT_DIR }}/${{ env.PROJECT_NAME }}-windows-${{ env.TAG_NAME }}.exe

  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    env:
      TAG_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          cd $PROJECT_PATH
          mkdir -v -p $EXPORT_DIR
          godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/${{ env.PROJECT_NAME }}-linux-${{ env.TAG_NAME }}.x86_64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ env.TAG_NAME }}
          path: ${{ env.EXPORT_DIR }}/${{ env.PROJECT_NAME }}-linux-${{ env.TAG_NAME }}.x86_64

  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    env:
      TAG_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          cd $PROJECT_PATH
          mkdir -v -p $EXPORT_DIR/${{ env.PROJECT_NAME }}-web-${{ env.TAG_NAME }}/
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/${{ env.PROJECT_NAME }}-web-${{ env.TAG_NAME }}/index.html"
      - name: Zip Web Build
        run: |
          cd build
          zip -r ${{ env.PROJECT_NAME }}-web-${{ env.TAG_NAME }}.zip ${{ env.PROJECT_NAME }}-web-${{ env.TAG_NAME }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-${{ env.TAG_NAME }}
          path: ${{ env.EXPORT_DIR }}/${{ env.PROJECT_NAME }}-web-${{ env.TAG_NAME }}.zip

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [export-windows, export-linux, export-web]
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-${{ github.ref_name }}
          path: build/

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-${{ github.ref_name }}
          path: build/

      - name: Download Web Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-${{ github.ref_name }}
          path: build/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/${{ env.PROJECT_NAME }}-windows-${{ github.ref_name }}.exe
          asset_name: ${{ env.PROJECT_NAME }}-${{ github.ref_name }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/${{ env.PROJECT_NAME }}-linux-${{ github.ref_name }}.x86_64
          asset_name: ${{ github.ref_name }}.x86_64
          asset_content_type: application/octet-stream

      - name: Upload Web Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/${{ env.PROJECT_NAME }}-web-${{ github.ref_name }}.zip
          asset_name: web-${{ github.ref_name }}.zip
          asset_content_type: application/zip
